name: Find Secret Defconfig

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - name: Fetch Official Xiaomi Kernel Source
      run: |
        git clone --depth=1 https://github.com/MiCode/Xiaomi_Kernel_OpenSource.git -b sunstone-u-oss kernel-source

    - name: Search Defconfig Files
      run: |
        cd kernel-source
        echo "🔍 जासूसी शुरू: arch/arm64/configs/ के अंदर मौजूद सारी फाइल्स की लिस्ट नीचे है 👇"
        find arch/arm64/configs/ -type f
        echo "🚨 लिस्ट प्रिंट हो गई है! अब हम प्रोसेस रोक रहे हैं।"
        exit 1
